/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.analizadorsintactico.frontend;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author rafael-cayax
 */
public class Editor extends javax.swing.JFrame {

    private int numFilas;
    private int ultimaColumna;
    private List<JLabel> filas;

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
        configurarEditor();
        numFilas = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        info = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        info.setText("Fila: 0 Columna: 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(info)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(info))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setMaximumSize(new java.awt.Dimension(50, 32767));
        jPanel3.setMinimumSize(new java.awt.Dimension(50, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 437));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }
    private javax.swing.JTextPane editor;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void configurarEditor() {
        editor = new javax.swing.JTextPane();
        filas = new ArrayList<>();
        JLabel primero = new JLabel("1");
        jPanel3.add(primero);
        jPanel2.add(editor, java.awt.BorderLayout.CENTER);
        editor.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                editor();
                actualizarPosicionCursor();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                editor();
                actualizarPosicionCursor();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }
            
        });
    }

    private void editor() {
        System.out.println(editor.getText());
            String f = editor.getText() + "f";
            char[] g = f.toCharArray();
            int cantidad = 1;
            for (char c : g) {
                if (c == '\n') {
                    cantidad++;
                }
            }
            if (cantidad != numFilas) {
                if (cantidad < numFilas) {
                    eliminarFila();
                } else if (cantidad > numFilas) {
                    agregarFila();
                }
            }
    }

    private void agregarFila() {
        numFilas++;
        String fila = numFilas + "";
        JLabel nuevaFila = new JLabel(fila);
        jPanel3.add(nuevaFila);
        this.filas.add(nuevaFila);
        this.repaint();
    }

    private void eliminarFila() {
        numFilas--;
        JLabel fila = filas.removeLast();
        jPanel3.remove(fila);
        this.repaint();
    }
    
    private void actualizarPosicionCursor() {
        try {
            int caretPos = editor.getCaretPosition();
            int fila = editor.getDocument().getDefaultRootElement().getElementIndex(caretPos) + 1;

            // Obtener el texto hasta el caret y detectar si se hizo un salto de línea
            String textoHastaCaret = editor.getText(0, caretPos);
            boolean esSaltoDeLinea = textoHastaCaret.endsWith("\n");

            if (esSaltoDeLinea) {
                // Si es un salto de línea, mantenemos la columna anterior
                int startOfPrevLine = editor.getDocument().getDefaultRootElement().getElement(fila - 2).getStartOffset();
                ultimaColumna = caretPos - startOfPrevLine;
            } else {
                // Obtener la columna normal
                int startOffset = editor.getDocument().getDefaultRootElement().getElement(fila - 1).getStartOffset();
                ultimaColumna = caretPos - startOffset + 1;
            }

            // Actualizar el label con la fila y la columna
            info.setText("Fila: " + fila + ", Columna: " + ultimaColumna);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
