/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.analizadorsintactico.frontend;

import com.mycompany.analizadorsintactico.Graficador;
import com.mycompany.analizadorsintactico.token.Token;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author rafael-cayax
 */
public class GraficosVista extends javax.swing.JFrame {

    /**
     * Creates new form GraficosVista
     */
    public GraficosVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelGradicos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelGradicos.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(panelGradicos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void agregarTablas(List<List<Token>> tablas){
        int filas = 0;
        int columnas = 0;
        for(List<Token> t : tablas){
            Graficador d = new Graficador();
            d.crearTabla(t);
            JLabel label = new JLabel();
            ImageIcon image = new ImageIcon(d.getImagenLexema());
            label.setIcon(image);
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = columnas;
            gbc.gridy = filas;
            columnas++;
            if (columnas == 3) {
                filas++;
                columnas = 0;
            }
            panelGradicos.add(label, gbc);
        }
        panelGradicos.repaint();
        panelGradicos.revalidate();
        this.pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGradicos;
    // End of variables declaration//GEN-END:variables
}
